### ISSUE TITLE
Migrate the existing Google Doc to here

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-maturity-matrix#1]
# Project

The Maturity Matrix is currently in a Google Doc and we need to migrate the content across to markdown files in this repository

https://docs.google.com/document/d/1wa2lliXQeH6HE1JHqwjTFuVndRUXzxGlbYXRtTQxF5o/edit

# Actions

- [x] @aecurrie close all open comments
- [x] @aecurrie lock Google Doc for further contributions
- [x] Identify which content is the actual Maturity Model and which is context
- [x] Agree how we are going to store the model content in markdown
- [x] Create markdown files from Google Doc
- [x] @aecurrie add banner to Google Doc redirecting to this GitHub repo
- [x] Setup DNS for GH pages custom domain

**Comment by russelltrow** [comment]
Content has been migrated and GitHub Pages setup: https://green-software-foundation.github.io/green-software-maturity-matrix/gsmm/

**Comment by russelltrow** [comment]
Hey @osamajandali could you setup a DNS entry for maturity-matrix.greensoftware.foundation for the GitHub pages site above please?

**Comment by osamajandali** [comment]
Hey @russelltrow 
I've added the DNS entry, should work now.
FYI, there is a docs template that is pre-configure and pre-styles with GSF branding, you can find it here https://github.com/Green-Software-Foundation/doc-template

**Comment by russelltrow** [comment]
@aecurrie could you add a banner to your Google Doc redirecting people to the GSF version please

**Comment by aecurrie** [comment]
Banner added to Google doc redirecting here
