### ISSUE TITLE
Logo for Green Software Maturity Matrix project

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-maturity-matrix#2]

**Comment by Jenya-design** [comment]
@russelltrow please let me know your thoughts about these options
Thank you

![Image](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/69306070/7efc6fca-7939-41ea-8c39-66e86eb642e2)

**Comment by russelltrow** [comment]
@aecurrie what do you think?

**Comment by aecurrie** [comment]
They both look good but number 1 is definitely more like what we are doing.
Number 1!

**Comment by Jenya-design** [comment]
Thank you @russelltrow @aecurrie 
Please find svg and png files for v.01 here
https://drive.google.com/drive/folders/1RshHwegW3xKj6toSS6ZNqTBlujmGUeBb?usp=drive_link

**Comment by russelltrow** [comment]
Amazing thank you!

**Comment by russelltrow** [comment]
![docusaurus-social-card](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/11027021/8702496f-86f6-41eb-ae58-c06c5a325685)

@Jenya-design would you mind doing a social card based on the attached image size as well please?

**Comment by Jenya-design** [comment]
Sure @russelltrow just Maturity Matrix logo there ?

**Comment by Jenya-design** [comment]
@russelltrow @aecurrie please check the social card, let me know if you prefer more complicated design with extra illustrations 

![Image](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/69306070/7b889610-445c-4692-a5cd-1dd8ee96df2b)

![Image](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/69306070/a3a58845-1077-456f-aa1f-5f125e957788)

**Comment by aecurrie** [comment]
Looks great to me!
