### ISSUE TITLE
Keep the OUSE & GSMM projects in sync

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-maturity-matrix#29]
# Context

There is potential for overlap between the "Organisation usage of Software Emissions" and "Green Software Maturity Matrix" projects. The Project team should meet on a regular basis to stay in sync and identify opportunity for collaboration.

# Acceptance Criteria

- [ ] Regular call organised between GSMM and OUSE projects

# Actions

- [x] Schedule a first sync call
- [x] Agree cadence for future meetings

**Comment by russelltrow** [comment]
@aecurrie @PindyBhullar how about this Friday for a first sync call?

Would 11:30, 12:00, 12:30 or 13:00 GMT?

**Comment by aecurrie** [comment]
I could do earlier or later.

**Comment by russelltrow** [comment]
## Meeting Notes - 12 Jan

* Agreed to establish a re-occurring monthly meeting.
* Next meeting on Friday 9th February at 11:00 GMT

### OUSE ("OOZ")

* Terms of Reference document shared with Asim & Sean
* FinOps setting up a [Sustainability Working Group](https://www.finops.org/wg/sustainability/)
  *  [Cloud Environmental Sustainability 101 - Assessment & Education](https://docs.google.com/spreadsheets/d/1Ewx4-QTWV8XqfkhQbimT6yPjrlQgDtkTlqNLEDqlLq4/edit#gid=2122288252)
  * Working to finalise project scope
* Will be forming an Action Research Group
* Timeline is over the next 12 months

### GSMM

* CNCF TAG Env might be [working on a maturity model](https://github.com/cncf/tag-env-sustainability/issues/50)
  * Based on Cloud Native maturity model https://maturitymodel.cncf.io/level-1/
* Still initiating the project - https://github.com/Green-Software-Foundation/green-software-maturity-matrix/milestone/1
  * Organising Project Kick-off for later in Jan
