### ISSUE TITLE
We need a GSMM graphic/image representation

### ISSUE THREAD

**Issue by aecurrie** [Green-Software-Foundation/green-software-maturity-matrix#3]
a lightly branded version for the O'Reilly book "Building Green Software" and then a full on GSF version for us.

As a reference, here is one Container Solutions did for the Cloud Native world:

https://info.container-solutions.com/cloud-maturity-matrix

Here are the GSF equivalents in doc form https://docs.google.com/document/d/1wa2lliXQeH6HE1JHqwjTFuVndRUXzxGlbYXRtTQxF5o/edit?usp=sharing

What that means is across the top the 5 items (columns) on the x axis are: Aspiring, Aware, Acting, Awesome, Inspiring

Downwards (rows) on the Y axis we have:
Commitments: None, Carbon Neutral, Carbon Zero with offsets, 10% offsets, 1% offsets
Footprint: Unknown, know scope 1/2, reducing per unit, reducing absolutely, ~zero 
Metrics: None, report scope 1&2, daily scope 1&2&3, realtime, predicted 
Carbon Ops: None, manual, Lightswitch Ops, auto-rightsizing, carbon SRE
Energy: None, green hosting, dynamic mgmt, demand shaping, 24/7 CFE
Devices: None, some targets, 10y/90%, 10y/100%, Theseus' Ship
Utilization: None, some multi-tenant, all multi-tenant, max orchestration, edge integration
Products: None, carbon awareness, demand shaping, feature tracking,  feature carbon error budgets
Training: Adhoc, basic/champions, advanced, you are the trainer, you are the leader

**Comment by russelltrow** [comment]
Hey @Jenya-design is this something you could help us with please?

**Comment by Jenya-design** [comment]
Hello @aecurrie  @russelltrow please let me know the deadline and do you need this as an image or editable canva design is better? Thank you

**Comment by russelltrow** [comment]
> Hello @aecurrie @russelltrow please let me know the deadline and do you need this as an image or editable canva design is better? Thank you

A Canva please as it might evolve over time. Deadline wise, would end of November be possible?

**Comment by Jenya-design** [comment]
Thank you @russelltrow , sure, I'll send you the update for review next week

**Comment by Jenya-design** [comment]
Note for me:
Placement of the image [in GSMM doc](https://docs.google.com/document/d/1tGS4rVPjyB3pUDS808uN4PKt00fHvIZVcrjXaxj5hB0/edit)

**Comment by Jenya-design** [comment]
@russelltrow @aecurrie please check two options for GSMM image and let me know if the structure is correct
I can add icons to the Y axis to make it more engaging, what do you think?

v.01
![Image](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/69306070/f490b695-be03-41f9-a1c0-5ea1d12ac0e0)

v.02
![Image](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/69306070/e69f82de-06a3-442b-af09-f0eda00584db)

**Comment by aecurrie** [comment]
Hi Jenya,

I love version 1!!!! I think icons on the y axis would be fab.

Some minor markups:
Footprint/Aware: Lets make it: "know scope 1&2"
Lets lower the case of all the starting capitals on the first column for
consistency
commitment/awesome should be: "10% (offset)"
commitment/inspiring should be: "1% (offset)"

WDYT?

**Comment by aecurrie** [comment]
And the columns should be highlighted like in v2 rather than the rows

**Comment by Jenya-design** [comment]
@aecurrie please check the update attached and let me know what you think

![Image](https://github.com/Green-Software-Foundation/green-software-maturity-matrix/assets/69306070/7f255ac3-b02e-4291-9eb4-91982cee75ad)

**Comment by aecurrie** [comment]
Fab!!! That can go straight in the O'Reilly book!

**Comment by Jenya-design** [comment]
@aecurrie you mentioned you need two versions: for book "Building Green Software" and then a full on GSF version for us.
But this one is already GSF branded. Will it work for both cases or you need the alternative? Do you need version for print or in higher resolution?

**Comment by aecurrie** [comment]
Good point! I will eventually need a hi def version. I think that version
will work fine in the OReilly book. It's really nice looking

**Comment by russelltrow** [comment]
It looks great. I've a few comments:

* Why are some rows taller than others? Are they more important? Would consistency be better?
* Could text be vertically aligned in rows for neatness?
* Should capitalisation be consistent? All initial lower or upper
* @aecurrie Can we replace any of the acronyms? e.g. mgmt, CFE
* @aecurrie Will enough people be aware of "Thesaus' ship"?

**Comment by aecurrie** [comment]
If we can fit in replacement of the acronyms that would be good
mgmt = management
CFE = Carbon Free Electricity
SRE = SRE
Theseus's ship = rolling repair

**Comment by Jenya-design** [comment]
@russelltrow @aecurrie thank your for your feedback, please check if I applied it correctly
https://docs.google.com/presentation/d/1KS3Gzik0iMLPOWLJSGQGOsrihAL0sD48HzksEGBLFCI/edit?usp=sharing

Apologies, I was caught up in Decarb design work and forgot that you need this piece editable
I tried canva, but it was a bit hard to edit the table there, so I made Google Slide 
I removed some elements on the side, so it's easier for you to rescale if necessary

Current size 1920x1080px (it's bigger that A4), all icons are in 300 dpi res, so it's good for print in that regard
For web you can download as png or web. For print - use 'print' option. 
If you know the approximate size of the printed piece - please let me know and I'll make a test print to check the font size

Folder with all files 
https://drive.google.com/drive/folders/1a5qEdjI0s4bN1QP2MVvnftGJB4cJbFAB?usp=drive_link

Let me know if you have any issues with access or need any adjustments

**Comment by aecurrie** [comment]
Looks great, thank you!

**Comment by russelltrow** [comment]
Absolutely beautiful, thank you @Jenya-design. A slide deck should work well, easy for us to keep tweaking.
