### ISSUE TITLE
[MOTION] Appoint Pini Reznik as Project Co-Lead

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-maturity-matrix#33]
## Motion

Appoint @pinireznik as an additional Project Lead for the Green Software Maturity Matrix (GSMM) project.

## Context

@aecurrie the GSMM Project Lead would like to appoint Pini as an additional Project Lead to support her in driving the project the forward.

## Actions

- [x] GSMM project members provide any comments or objections on this issue
- [x] Pending any unresolved objections Pini will be appointed on Wednesday 8th May 2024

**Comment by muemich** [comment]
+1

**Comment by russelltrow** [comment]
@aecurrie @pinireznik I am pleased to confirm that the motion passed without objection. @pinireznik is officially appointed as an additional Project Lead.

**Comment by aecurrie** [comment]
Hurray!

**Comment by pinireznik** [comment]
Can’t wait to start contributing. Have some ideas already.
