### ISSUE TITLE
Organise a Project Kick-off

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/green-software-maturity-matrix#5]
# Context

We would like to hold a project kick-off with all interested parties:

* Take place in mid January 2024
* Held virtually on Zoom

All interested parties should subscribe to the project to be automatically added to the calendar invite: 

https://greensoftware.foundation/subscribe

The meeting will be documented on the project wiki: 

https://github.com/Green-Software-Foundation/green-software-maturity-matrix/wiki/2024%E2%80%9001%E2%80%90XX:-Project-Kick%E2%80%90off

# Resources

* [Agenda Google Doc](https://docs.google.com/document/d/1P4AE90R-YfgQbqixnIeDEbwtRWX68SD9AEaAh6ND0-I/edit#heading=h.b6ygb76ogd5y)

# Actions

- [x] @aecurrie @russelltrow agree a Date & Time
- [x] @russelltrow create calendar invite
- [x] @aecurrie define initial participant list
- [x] @russelltrow  announce meeting to CWG
- [ ] @aecurrie @pinireznik build agenda

**Comment by imdacharlene** [comment]
+1 to attend. Any friendly asia timezone?

**Comment by russelltrow** [comment]
@aecurrie how about holding the session on either Monday 15, Friday 19, Tuesday 23 or Thursday 25 January? All of these days have few GSF WG/Project calls happening.

**Comment by aecurrie** [comment]
Thursday 25th?

**Comment by russelltrow** [comment]
> Thursday 25th?

What time shall we hold it?

**Comment by aecurrie** [comment]
the whole day is free for me so what do we reckon? We could do 2 calls?

**Comment by russelltrow** [comment]
Moving to 8th February. Will schedule morning and afternoon calls.

**Comment by russelltrow** [comment]
Kick-off moved to Thursday 15th February due to a conference clash. New calendar invites sent out.

**Comment by russelltrow** [comment]
@aecurrie @pinireznik for when should we schedule the kick-off?

**Comment by pinireznik** [comment]
Last week of June?

**Comment by russelltrow** [comment]
How about Thursday 27th June at [15:00 UTC](https://everytimezone.com/s/967db5aa)?

**Comment by pinireznik** [comment]
works for me

**Comment by aecurrie** [comment]
and me

**Comment by russelltrow** [comment]
@aecurrie @pinireznik I've just shared a template presentation deck with you

**Comment by russelltrow** [comment]
Notes: https://github.com/Green-Software-Foundation/green-software-maturity-matrix/discussions/38
